# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import sentiment_analytic_pb2 as sentiment__analytic__pb2


class SentimentAnalyticStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeSentiment = channel.unary_unary(
                '/SentimentAnalytic.SentimentAnalytic/AnalyzeSentiment',
                request_serializer=sentiment__analytic__pb2.InputFile.SerializeToString,
                response_deserializer=sentiment__analytic__pb2.OutputFile.FromString,
                )


class SentimentAnalyticServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AnalyzeSentiment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SentimentAnalyticServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeSentiment': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeSentiment,
                    request_deserializer=sentiment__analytic__pb2.InputFile.FromString,
                    response_serializer=sentiment__analytic__pb2.OutputFile.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SentimentAnalytic.SentimentAnalytic', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SentimentAnalytic(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeSentiment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SentimentAnalytic.SentimentAnalytic/AnalyzeSentiment',
            sentiment__analytic__pb2.InputFile.SerializeToString,
            sentiment__analytic__pb2.OutputFile.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
